services:
  - type: web
    name: codeigniter-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        value: YOUR_RENDER_DB_HOST
      - key: DB_NAME
        value: YOUR_RENDER_DB_NAME
      - key: DB_USER
        value: YOUR_RENDER_DB_USER
      - key: DB_PASS
        value: YOUR_RENDER_DB_PASSWORD
